#!/bin/sh
# postinst script for softether-vpn package

set -e
ANSI_RED='\033[0;31m'
ANSI_GREEN='\033[0;32m'
ANSI_YELLOW='\033[1;33m'
ANSI_RESET='\033[0m'

PATH_INSTALL=/usr/local/softether/vpnclient
PATH_LOG=/var/log/softether-vpn.log

case "$1" in
    configure)
        echo
        echo "${ANSI_GREEN} Running SoftEther VPN post-install script ${ANSI_RESET}"
        echo

        touch ${PATH_LOG}
        chmod 0666 ${PATH_LOG}
        echo "Created log ${ANSI_YELLOW}${PATH_LOG}${ANSI_RESET} file"

        ln --symbolic --force ${PATH_INSTALL}/softether-vpnclient.service /etc/systemd/system/

        echo "Symlink ${ANSI_GREEN}created${ANSI_RESET}"

        echo "Updating dependencies..."
        # apt-get -y install isc-dhcp-client openssl ncurses-base
        echo "${ANSI_GREEN}Ok.${ANSI_RESET}"
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0